name: Continuos Integration

on:
  push:
    branches:
      - master
      - develop

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm
      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: |
          pnpm --filter='./packages/types' build \
            && pnpm --filter='./packages/common' build \
            && pnpm --filter='./packages/entrypoint' build \
            && pnpm --filter='./packages/validation' build \
            && pnpm --filter='./packages/http' build \
            && pnpm --filter='./packages/node-http' build \
            && pnpm --filter='./packages/access-control' build \
            && pnpm --filter='./packages/security' build \
            && pnpm --filter='./packages/core' build \
            && pnpm --filter='./packages/builtins' build \
            && pnpm --filter='./packages/server' build \
            && pnpm --filter='./packages/aeria-sdk' build \
            && pnpm --filter='./packages/cli' build \
            && pnpm --filter='./packages/aeria' build

      - name: Generate packages/builtins-icons
        run: pnpm --filter='./packages/builtins' write-icons

      - name: Run tests
        run: pnpm -r test

      - name: Build playground
        run: |
          pnpm --filter=playground build

      - name: Test
        env:
          A: ${{ github.head_ref }}
          B: ${{ github.ref_name  }}
          BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
        run: |
          echo $A
          echo $B
          echo $BRANCH_NAME

      - name: Create release PR
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

